# Generated by Django 4.2.17 on 2024-12-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_created=True)),
                ('game_code', models.CharField(max_length=5)),
                ('player_1_code', models.CharField(max_length=10)),
                ('player_2_code', models.CharField(max_length=10)),
                ('fields_chess', models.JSONField()),
                ('current_player_turn', models.IntegerField()),
                ('winner_player', models.IntegerField()),
            ],
        ),
    ]
